### ISSUE TITLE
Unable to connect inside kubernetes deployment

### ISSUE THREAD

**Issue by musedivision** [zilliztech/milvus-insight#238]
**Describe the bug:**
I have deployed insight on my k8s cluster which is running a milvus 2 deployment

While the container seems to be running I cannot connect to the `insight` server

**Steps to reproduce:**
1. deploy to k8s on default namespace with following manifests
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: milvus-insight
  name: milvus-insight
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: milvus-insight
  template:
    metadata:
      labels:
        app: milvus-insight
    spec:
      containers:
      - name: insight
        image: milvusdb/milvus-insight:latest
        env:
        - name: HOST_URL
          value: http://milvus-insight.default.svc.cluster.local:8000
        - name: MILVUS_URL
          value: "milvus.default.svc.cluster.local:19530"
        ports:
          - containerPort: 8000
            name: http
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-insight
  labels:
    app: milvus-insight
spec:
  selector:
    app: milvus-insight
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http

```
2. port forward milvus to `localhost:8000`
3. curl -v localhost:8000
get response 
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /home HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.58.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Milvus-insight version:**
`milvusdb/milvus-insight:latest`

**Milvus version:**
2.2.0 (from helm release )
